export const SET_QUESTIONLAYOUT = 'SET_QUESTIONLAYOUT';
export type SET_QUESTIONLAYOUT = typeof SET_QUESTIONLAYOUT;

export const SET_TEMPLAYOUT = 'SET_TEMPLAYOUT';
export type SET_TEMPLAYOUT = typeof SET_TEMPLAYOUT;

export const SET_OVERLAYOUT = 'SET_OVERLAYOUT';
export type SET_OVERLAYOUT = typeof SET_OVERLAYOUT;

export const NEWGAME = 'NEWGAME';
export type NEWGAME = typeof NEWGAME;

export const RESTARTGAME = 'RESTARTGAME';
export type RESTARTGAME = typeof RESTARTGAME;